# Generated by Django 2.2.8 on 2019-12-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_photos', to='user_app.UserModel'),
        ),
    ]
