# Generated by Django 2.2.8 on 2019-12-22 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0002_auto_20191220_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='photo_app.PostModel'),
        ),
    ]
