# Generated by Django 2.2.8 on 2019-12-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0003_auto_20191222_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='likes',
        ),
    ]
