# Generated by Django 2.2.8 on 2019-12-20 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='emnail',
            new_name='email',
        ),
    ]
